site_name: FastAPIMKDocs

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [.]
nav:
  - documentation: index.md

theme:
  name: readthedocs
  custom_dir: custom_theme/
  highlightjs: false
